### ISSUE TITLE
Rename to something different than Crux

### ISSUE THREAD

**Issue by corsinconzett** [datascaled/fred-js#1]
`[crux.land](https://crux.land/)` exists which might be confused with `crux-js`.

Proposals:
- `cory-js`: derived from `core`, e.g. `@cory/event-bus`
- `lou-js`: acronym for `library of utilities`, e.g. `@lou/event-bus`
- `love-js`: acronym for `library of versatile essentials`, e.g. `@love/event-bus`

Open for other suggestions.

**Comment by ramoneg** [comment]
lou-js looks good to me (or lou'ks good to me).
